# https://www.javierbrea.com/blog/spellcheck-github-action/

name: Spellcheck
run-name: run spellcheck for ${{ github.actor }}'s new code
on: [push]
jobs:
  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Spelling
        uses: rojopolis/spellcheck-github-actions@0.29.0
        with:
          config_path: .spellcheck.yaml
          task_name: Markdown